=== jubarajmukherjee/cat1_wsd/CAT 1/2/test2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/sample" xmlns:rt="http://www.example.org/sample"
elementFormDefault="qualified">
    <xs:element name="college">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" minOccurs="0" maxOccurs="100">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Stu-name" type="xs:string"/>
                            <xs:element name="Stu-Course" type="xs:string"/>
                            <xs:element name="Stu-Sem" type="xs:integer"/>
                            <xs:element name="Stu-Sub1" type="xs:integer"/>
                            <xs:element name="Stu-Sub2" type="xs:integer"/>
                            <xs:element name="Stu-Sub3" type="xs:integer"/>
                            <xs:element name="Stu-Total" type="xs:integer"/>
                            <xs:element name="Stu-Avg" type="xs:integer"/>
                            
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Stu-Sub1">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="100"></xs:minInclusive>
                            <xs:maxInclusive value="0"></xs:maxInclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
</xs:schema>

=== jubarajmukherjee/cat1_wsd/CAT 1/2/test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="test3.xsl" type="text/xsl"?>
<college xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/sample test2.xsd">
    <student>
        <Stu-name>A Mukherjee</Stu-name>
        <Stu-Course>MCA</Stu-Course>
        <Stu-Sem>2</Stu-Sem>
        <Stu-Sub1>40</Stu-Sub1>
        <Stu-Sub2>40</Stu-Sub2>
        <Stu-Sub3>40</Stu-Sub3>
        <Stu-Total>120</Stu-Total>
        <Stu-Avg>40</Stu-Avg>
    </student>
    <student>
        <Stu-name>B Das</Stu-name>
        <Stu-Course>MCA</Stu-Course>
        <Stu-Sem>2</Stu-Sem>
        <Stu-Sub1>95</Stu-Sub1>
        <Stu-Sub2>85</Stu-Sub2>
        <Stu-Sub3>90</Stu-Sub3>
        <Stu-Total>270</Stu-Total>
        <Stu-Avg>90</Stu-Avg>
    </student>
    <student>
        <Stu-name>J Haldar</Stu-name>
        <Stu-Course>MCA</Stu-Course>
        <Stu-Sem>2</Stu-Sem>
        <Stu-Sub1>50</Stu-Sub1>
        <Stu-Sub2>70</Stu-Sub2>
        <Stu-Sub3>90</Stu-Sub3>
        <Stu-Total>210</Stu-Total>
        <Stu-Avg>70</Stu-Avg>
    </student>
    <student>
        <Stu-name>N Iyer</Stu-name>
        <Stu-Course>MCA</Stu-Course>
        <Stu-Sem>2</Stu-Sem>
        <Stu-Sub1>80</Stu-Sub1>
        <Stu-Sub2>80</Stu-Sub2>
        <Stu-Sub3>83</Stu-Sub3>
        <Stu-Total>243</Stu-Total>
        <Stu-Avg>81</Stu-Avg>
    </student>
    <student>
        <Stu-name>G Bose</Stu-name>
        <Stu-Course>MCA</Stu-Course>
        <Stu-Sem>2</Stu-Sem>
        <Stu-Sub1>49</Stu-Sub1>
        <Stu-Sub2>45</Stu-Sub2>
        <Stu-Sub3>56</Stu-Sub3>
        <Stu-Total>150</Stu-Total>
        <Stu-Avg>50</Stu-Avg>
    </student>
</college>
